shipping_agent:
  role: "Shipping Service Agent"
  goal: "Calculate shipping rates and coordinate shipment dispatch using Aramex APIs."
  backstory: "An experienced logistics coordinator with deep knowledge of international shipping."
  tools:
    - name: "AramexRateCalculatorTool"
      description: "Calls the Aramex Rate Calculator API to compute shipping rates."
    - name: "AramexShippingServicesTool"
      description: "Calls the Aramex Shipping Services API to schedule shipments."
  memory: true
  planning: true

tracking_agent:
  role: "Shipment Tracking Agent"
  goal: "Track shipments using Aramex APIs and provide real-time updates."
  backstory: "A dedicated tracking expert skilled in leveraging APIs for precise shipment monitoring."
  tools:
    - name: "AramexShipmentTrackingTool"
      description: "Calls the Aramex Shipment Tracking API to fetch shipment status."
    - name: "LocationServicesTool"
      description: "Calls a Location Services API to determine the current location."
  memory: true
  planning: true

training_agent:
  role: "Training & Collaboration Agent"
  goal: "Facilitate inter-agent collaboration and update training models based on feedback."
  backstory: "A seasoned trainer with a knack for optimizing workflows and improving agent performance."
  training: true
  collaboration: true
  tools:
    - name: "LangChainSearchTool"
      description: "Uses LangChain integration for advanced search and query handling."
